---
spring:
  application:
    name: app-springboot
  profiles: ${spring.application.name}
  freemarker:
    cache: false

server:
  connection-timeout: 5000
  port: 8080
  compression:
    enabled: true
    min-response-size: 1

keycloak:
  realm: NowCP
  auth-server-url: http://localhost:8180/auth
  ssl-required: external
  public-client: true
  resource: ${spring.application.name}
  principal-attribute: preferred_username

products:
  service:
    url: http://localhost:8081/



